# Generated by Django 4.1.4 on 2023-03-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='nm_prof',
            new_name='id_prof',
        ),
    ]
