# Generated by Django 4.1.4 on 2023-03-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_rename_nm_prof_cours_id_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='id_prof',
            field=models.IntegerField(),
        ),
    ]
