# Generated by Django 4.1.4 on 2023-03-07 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prof', '0003_alter_cours_id_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='id_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
