# Generated by Django 4.1.4 on 2023-03-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_alter_cours_id_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='id_prof',
            new_name='nm_prof',
        ),
    ]
