# Generated by Django 4.1.4 on 2023-03-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_rename_id_prof_cours_nm_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='nm_prof',
            field=models.CharField(max_length=150, null=None),
        ),
    ]
