# Generated by Django 4.1.4 on 2023-01-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authmodel',
            old_name='last_password',
            new_name='last_login',
        ),
    ]
