# Generated by Django 4.1.4 on 2023-01-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_rename_last_password_authmodel_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authmodel',
            old_name='last_login',
            new_name='last_password',
        ),
    ]
