# Generated by Django 4.1.4 on 2023-01-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_rename_last_login_authmodel_last_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authmodel',
        ),
    ]
