# Generated by Django 4.1.4 on 2023-02-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('nm_service', models.CharField(max_length=100)),
                ('stud', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
