# Generated by Django 4.1.4 on 2023-02-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nm_service',
            field=models.CharField(choices=[('Relevé de note', 'Relevé de note'), ('Attestation de résultats', 'Attestation de résultats'), ('Attestation de scolarité', 'Attestation de scolarité'), ('Attestation de réussite', 'Attestation de réussite'), ('Copie conforme baccalauréat', 'Copie conforme baccalauréat'), ('baccalauréat provisoire', 'baccalauréat provisoire'), ('Diplome DUT', 'Diplome DUT'), ('Diplome Licence', 'Diplome Licence'), ('baccalauréat definitif', 'baccalauréat definitif'), ('Carte etudiant', 'Carte etudiant')], max_length=100),
        ),
    ]
