# Generated by Django 4.1.4 on 2023-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_alter_service_nm_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='stud',
            new_name='nm_dem',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='nm_service',
            new_name='type_service',
        ),
        migrations.AddField(
            model_name='service',
            name='date_dem',
            field=models.DateField(default=None),
        ),
    ]
