# Generated by Django 4.1.4 on 2023-03-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0003_rename_stud_service_nm_dem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('nm_filiere', models.CharField(default=None, max_length=100)),
                ('module', models.CharField(default=None, max_length=100)),
                ('note', models.IntegerField()),
                ('Resultat', models.CharField(default=None, max_length=100)),
                ('Annee', models.IntegerField()),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
