# Generated by Django 4.1.4 on 2023-03-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0004_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notes',
        ),
    ]
