# Generated by Django 4.1.4 on 2023-03-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0009_delete_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
    ]
