# Generated by Django 4.1.4 on 2023-03-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Annee',
            field=models.IntegerField(default=0.9995056846267919),
        ),
        migrations.AddField(
            model_name='notes',
            name='matiere',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='notes',
            name='note',
            field=models.IntegerField(default=None),
        ),
    ]
