# Generated by Django 4.1.4 on 2023-03-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0012_notes_annee_notes_matiere_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='resultat',
            field=models.CharField(choices=[('V', 'v'), ('R', 'r')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='notes',
            name='session',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=1, max_length=50),
        ),
    ]
