# Generated by Django 4.1.4 on 2023-03-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0013_notes_resultat_notes_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='filiere',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
