# Generated by Django 4.1.4 on 2023-03-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0014_alter_notes_filiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notes',
        ),
    ]
