# Generated by Django 4.1.4 on 2023-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stud', '0015_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('filiere', models.CharField(default=None, max_length=50)),
                ('matiere', models.CharField(default=None, max_length=50)),
                ('resultat', models.CharField(choices=[('V', 'v'), ('R', 'r')], default=None, max_length=50)),
                ('session', models.CharField(choices=[('1', '1'), ('2', '2')], default=1, max_length=50)),
                ('note', models.IntegerField(default=None)),
                ('Annee', models.IntegerField(default=0.9995056846267919)),
            ],
        ),
    ]
