# Generated by Django 4.1.4 on 2023-03-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0016_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='etud',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
