# Generated by Django 4.1.4 on 2023-03-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0017_notes_etud'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('is_service', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Attestastion de scolarité', 'Attestastion de scolarité'), ('Relevé de Notes', 'Relevé de Notes'), ('Attestation de résultats', 'Attestation de résultats'), ('Attestastion de réussite', 'Attestastion de réussite'), ('Copie conforme baccalauréat', 'Copie conforme baccalauréat'), ('Baccalauréat provisoire', 'Baccalauréat provisoire'), ('Diplome licence', 'Diplome licence'), ('Carte étudiant', 'Carte étudiant'), ('Signer un document', 'Signer un document')], max_length=50)),
            ],
        ),
    ]
