# Generated by Django 4.1.4 on 2023-03-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0018_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='type',
            new_name='type_s',
        ),
    ]
