# Generated by Django 4.1.4 on 2023-03-03 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stud', '0019_rename_type_services_type_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='suiv_serv',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('nm_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stud.services')),
            ],
        ),
    ]
