# Generated by Django 4.1.4 on 2023-03-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0020_suiv_serv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable', models.FileField(upload_to='timetables/')),
            ],
        ),
    ]
