# Generated by Django 4.1.4 on 2023-03-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0021_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
