# Generated by Django 4.1.4 on 2023-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0023_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
    ]
