# Generated by Django 4.1.4 on 2023-03-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0025_alter_pdffile_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='title',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='emp_filiere',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], default=False, max_length=200, null=None),
        ),
    ]
