# Generated by Django 4.1.4 on 2023-03-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0026_remove_pdffile_title_pdffile_emp_filiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
