# Generated by Django 4.1.4 on 2023-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0028_notes_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='semestre',
            field=models.CharField(choices=[('S1', 's1'), ('S2', 's2'), ('S3', 's3'), ('S4', 's4'), ('S5', 's5'), ('S6', 's6')], default=False, max_length=50),
        ),
    ]
