# Generated by Django 4.1.4 on 2023-03-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0029_alter_notes_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='filiere',
        ),
    ]
