# Generated by Django 4.1.4 on 2023-03-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0030_remove_notes_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('nm_cours', models.CharField(default=False, max_length=30)),
                ('nm_prof', models.CharField(default=False, max_length=30)),
                ('filiere_cours', models.CharField(default=False, max_length=30)),
                ('niv_cours', models.CharField(default=False, max_length=30)),
            ],
        ),
    ]
