# Generated by Django 4.1.4 on 2023-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0031_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
