# Generated by Django 4.1.4 on 2023-03-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0032_cours_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='pdf_cours',
            field=models.FileField(default=False, upload_to='pdfsExam/'),
        ),
    ]
