# Generated by Django 4.1.4 on 2023-03-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0033_cours_pdf_cours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cours',
        ),
    ]
