# Generated by Django 4.1.4 on 2023-03-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0034_delete_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Annee',
        ),
        migrations.AlterField(
            model_name='notes',
            name='etud',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.FloatField(default=None),
        ),
    ]
