# Generated by Django 4.1.4 on 2023-03-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0035_remove_notes_annee_alter_notes_etud_alter_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Annee_unv',
            field=models.DateField(default=None),
        ),
    ]
