# Generated by Django 4.1.4 on 2023-03-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0036_notes_annee_unv'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='niv_cours',
            field=models.CharField(choices=[('Premiere annee', 'Premiere annee'), ('Deuxième annee', 'Deuxième annee'), ('Troisième annee', 'Troisième annee')], default=None, max_length=200),
        ),
    ]
