# Generated by Django 4.1.4 on 2023-03-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0037_notes_niv_cours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='niv_cours',
            new_name='niv_notes',
        ),
    ]
