# Generated by Django 4.1.4 on 2023-03-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0038_rename_niv_cours_notes_niv_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Annee_unv',
        ),
    ]
