# Generated by Django 4.1.4 on 2023-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0039_remove_notes_annee_unv'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Annee_unv',
            field=models.IntegerField(default=None),
        ),
    ]
