# Generated by Django 4.1.4 on 2023-02-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filiere',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('nm_filiere', models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], max_length=50)),
                ('chef_filiere', models.CharField(default='', max_length=50)),
                ('annee_univ', models.IntegerField()),
            ],
            options={
                'db_table': 'filiere',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=50),
        ),
        migrations.CreateModel(
            name='classeetud',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nm_stud', models.CharField(max_length=100)),
                ('niv_etud', models.CharField(choices=[('Premier', 'Premier'), ('Deuxieme', 'Deuxieme')], max_length=50)),
                ('nm_filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.filiere')),
            ],
            options={
                'db_table': 'classeetud',
            },
        ),
    ]
