# Generated by Django 4.1.4 on 2023-02-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_filiere_alter_user_role_classeetud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classeetud',
        ),
    ]
