# Generated by Django 4.1.4 on 2023-02-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_delete_classeetud'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nm_filiere',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adm.filiere'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nm_filiere',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='classeetud',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nm_stud', models.CharField(max_length=100)),
                ('niv_etud', models.CharField(choices=[('Premier', 'Premier'), ('Deuxieme', 'Deuxieme')], max_length=50)),
                ('nm_filiere', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adm.filiere')),
            ],
            options={
                'db_table': 'classeetud',
            },
        ),
    ]
