# Generated by Django 4.1.4 on 2023-02-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_user_nm_filiere_alter_filiere_nm_filiere_classeetud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='id_filiere',
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nm_filiere',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
