# Generated by Django 4.1.4 on 2023-02-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_remove_filiere_id_filiere_alter_filiere_nm_filiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classeetud',
            old_name='nm_filiere',
            new_name='filiere',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nm_filiere',
            new_name='filiere',
        ),
    ]
