# Generated by Django 4.1.4 on 2023-02-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_rename_nm_filiere_classeetud_filiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.ForeignKey(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], on_delete=django.db.models.deletion.CASCADE, to='adm.filiere'),
        ),
    ]
