# Generated by Django 4.1.4 on 2023-02-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_alter_user_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adm.filiere'),
        ),
    ]
