# Generated by Django 4.1.4 on 2023-02-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_alter_user_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], default='', max_length=50),
        ),
    ]
