# Generated by Django 4.1.4 on 2023-02-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_alter_user_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classeetud',
            name='niv_etud',
        ),
    ]
