# Generated by Django 4.1.4 on 2023-02-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0013_remove_classeetud_niv_etud'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='niv_stud',
            field=models.CharField(choices=[('Premiere annee', 'Premiere annee'), ('Deuxième annee', 'Deuxième annee'), ('Troisième annee', 'Troisième annee')], default='', max_length=50, null=True),
        ),
    ]
