# Generated by Django 4.1.4 on 2023-03-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_user_niv_stud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classeetud',
        ),
        migrations.DeleteModel(
            name='filiere',
        ),
    ]
