# Generated by Django 4.1.4 on 2023-03-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0015_delete_classeetud_delete_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_filiere', models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], default=False, max_length=200, null=None)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
