# Generated by Django 4.1.4 on 2023-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0016_pdffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='emp_role',
            field=models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'teacher')], default=False, max_length=50),
        ),
    ]
