# Generated by Django 4.1.4 on 2023-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0017_pdffile_emp_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='examens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_exam', models.CharField(choices=[('DS1', 'DS1'), ('DS2', 'DS2')], default=False, max_length=200, null=None)),
                ('exam_filiere', models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], default=False, max_length=200, null=None)),
                ('niv_filiere', models.CharField(choices=[('Premiere annee', 'Premiere annee'), ('Deuxième annee', 'Deuxième annee'), ('Troisième annee', 'Troisième annee')], default=False, max_length=200, null=None)),
                ('conv_exam', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
