# Generated by Django 4.1.4 on 2023-03-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0018_examens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examens',
            name='conv_exam',
            field=models.FileField(upload_to='pdfsExam/'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to='pdfsEmp/'),
        ),
    ]
