# Generated by Django 4.1.4 on 2023-03-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0019_alter_examens_conv_exam_alter_pdffile_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examens',
            name='exam_filiere',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='examens',
            name='niv_filiere',
            field=models.CharField(choices=[('Premiere annee', 'Premiere annee'), ('Deuxième annee', 'Deuxième annee'), ('Troisième annee', 'Troisième annee')], default=False, max_length=200),
        ),
    ]
