# Generated by Django 4.1.4 on 2023-03-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0020_alter_examens_exam_filiere_alter_examens_niv_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='niv_emp',
            field=models.CharField(choices=[('Premiere annee', 'Premiere annee'), ('Deuxième annee', 'Deuxième annee'), ('Troisième annee', 'Troisième annee')], default=False, max_length=200),
        ),
    ]
