# Generated by Django 4.1.4 on 2023-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0021_pdffile_niv_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_cours', models.CharField(default=False, max_length=200, null=None)),
                ('nm_prof', models.CharField(default=False, max_length=200)),
                ('filiere_cours', models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], default=False, max_length=200)),
                ('cours_pdf', models.FileField(upload_to='pdfsExam/')),
                ('niv_cours', models.CharField(choices=[('Premiere annee', 'Premiere annee'), ('Deuxième annee', 'Deuxième annee'), ('Troisième annee', 'Troisième annee')], default=False, max_length=200)),
            ],
        ),
    ]
