# Generated by Django 4.1.4 on 2023-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0022_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='cours_pdf',
            field=models.FileField(upload_to='pdfscours/'),
        ),
    ]
