# Generated by Django 4.1.4 on 2023-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0023_alter_cours_cours_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
