# Generated by Django 4.1.4 on 2023-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0024_cours_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='filiere_cours',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Management', 'Management'), ('Energie', 'Energie'), ('Electrique', 'Electrique')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cours',
            name='niv_cours',
            field=models.CharField(choices=[('Premiere annee', 'Premiere annee'), ('Deuxième annee', 'Deuxième annee'), ('Troisième annee', 'Troisième annee')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nm_cours',
            field=models.CharField(max_length=200, null=None),
        ),
    ]
