# Generated by Django 4.1.4 on 2023-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0025_alter_cours_filiere_cours_alter_cours_matiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='nm_prof',
            field=models.CharField(max_length=200),
        ),
    ]
