# Generated by Django 4.1.4 on 2023-03-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0026_alter_cours_nm_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cours',
        ),
    ]
