# Generated by Django 4.1.4 on 2023-03-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0027_delete_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='nm_prof',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
