# Generated by Django 4.1.4 on 2023-03-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0028_pdffile_nm_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='nm_prof',
            field=models.CharField(default='', max_length=200),
        ),
    ]
